import DERRMap from "c/derrmap";
import { createElement } from "lwc";

describe("c-derrmap", () => {
  const mockedValue = "mocked-value";
  beforeAll(() => {
    delete window.crypto;
    window.crypto = {
      randomUUID: jest.fn(() => mockedValue)
    };
  });

  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-derrmap", {
      is: DERRMap
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(element.nodeName).toBe("C-DERRMAP");
  });
});
